[WIP] Delete maintenance activity by id, List maintenance activity for given asset id
vkhichar/asset-management pull request #24
Opened 2021-03-05 06:42 UTC by ranbharerp15

Added apis for 
1) Delete maintenance activity by id
2) list all maintenance activities for given asset id

2021-03-05 06:48 UTC, ranbharerp15 commented
One question:
For list maintenance activities api, if asset_id is not present in db, should we return 404 error code?

In current implementation, it is returning empty array in response. As assets Apis are not available at the moment, I haven't added above check.

2021-03-07 05:18 UTC, vkhichar requested changes

2021-03-07 05:18 UTC, vkhichar commented on contract/asset_maintenance.go
> +	DATE_FORMAT = "2006-01-02" // yyyy-mm-dd
follow camel case for variable/constant names

2021-03-07 05:18 UTC, vkhichar commented on handler/util.go
> +var (
we already have a 'customerrors' package for this kind of errors

2021-03-07 05:18 UTC, vkhichar commented on handler/util.go
> +func ReadTokenFromRequest(r *http.Request) (string, error) {
move out of 'utils.go' file and create a separate file. this doesn't seems an utility

2021-03-07 05:18 UTC, vkhichar commented on handler/util.go
> +func ReadTokenFromRequest(r *http.Request) (string, error) {
Probably write a middleware and add that middleware to router level

2021-03-07 05:18 UTC, vkhichar commented on handler/util.go
> +	claims, err := deps.tokenService.ValidateToken(token)
dependencies should be injected. so that unit testing would be easy

2021-03-17 12:56 UTC, merged